name: Docker Nightly Build and Push
run-name: Docker Nightly Build @${{ inputs.release_type }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
        description: "Nightly release type. One of 'nightly-main', 'nightly-base', 'nightly-main-all'."
      ref:
        required: true
        type: string
        description: "Ref to check out (branch, tag, or commit). This is required -- it specifies where the source code for the release is located."
      push_to_registry:
        required: false
        type: boolean
        default: true
        description: "Whether to push images to registries. Set to false for testing builds without publishing."

  workflow_dispatch:
    inputs:
      release_type:
        description: "Nightly release type. One of 'nightly-main', 'nightly-base', 'nightly-main-all'."
        required: true
        type: choice
        options:
          - nightly-main
          - nightly-base
          - nightly-main-all
      ref:
        required: true
        type: string
        description: "Ref to check out (branch, tag, or commit). This is required -- it specifies where the source code for the release is located. Note that if running via Github Actions, this tag (formatted as, e.g., v1.5.1.dev36) must be manually created and pushed to a branch prior to running the workflow."
      push_to_registry:
        description: "Whether to push images to registries. Set to false for testing builds without publishing."
        required: false
        type: boolean
        default: false

env:
  PYTHON_VERSION: "3.13"

jobs:
  build-nightly-base:
    name: Build Nightly Base Package
    if: ${{ inputs.release_type == 'nightly-base' }}
    runs-on: [self-hosted, linux, ARM64, langflow-ai-arm64-40gb]
    steps:
      - name: Check out the code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Environment
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.13"
          prune-cache: false

      - name: Get version for tagging
        id: version
        run: |
          echo "Extracting base version from pyproject.toml"

          # Use the exact version from pyproject.toml (must already be formatted correctly)
          version=$(uv tree | grep 'langflow-base' | awk '{print $3}' | sed 's/^v//' | head -n 1)

          # Verify nightly tag format
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$ ]]; then
            echo "Base version format is incorrect. Must be in the format (e.g.) v1.5.1.dev36"
            exit 1
          fi

          echo "Using version: $version"
          echo version=$version >> $GITHUB_OUTPUT
      - name: Set nightly tags
        id: tags
        run: |
          version="${{ steps.version.outputs.version }}"
          echo "docker_tags=langflowai/langflow-nightly:base-${version},langflowai/langflow-nightly:base-latest" >> $GITHUB_OUTPUT
          echo "ghcr_tags=ghcr.io/langflow-ai/langflow-nightly:base-${version},ghcr.io/langflow-ai/langflow-nightly:base-latest" >> $GITHUB_OUTPUT

      - name: Docker cleanup
        run: |
          docker system prune -af --volumes || true
          docker buildx prune -af || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TEMP_GHCR_TOKEN}}

      - name: Build and push nightly base to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          file: ./docker/build_and_push_base.Dockerfile
          tags: ${{ steps.tags.outputs.docker_tags }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push nightly base to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          file: ./docker/build_and_push_base.Dockerfile
          tags: ${{ steps.tags.outputs.ghcr_tags }}
          platforms: linux/amd64,linux/arm64

  build-nightly-main:
    name: Build Nightly Main Package
    if: ${{ inputs.release_type == 'nightly-main' }}
    runs-on: [self-hosted, linux, ARM64, langflow-ai-arm64-40gb]
    steps:
      - name: Check out the code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Environment
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.13"
          prune-cache: false

      - name: Get version for tagging
        id: version
        run: |
          echo "Extracting main version from pyproject.toml"

          # Use the exact version from pyproject.toml (must already be formatted correctly)
          version=$(uv tree | grep 'langflow' | grep -v 'langflow-base' | awk '{print $2}' | sed 's/^v//')

          # Verify nightly tag format
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$ ]]; then
            echo "Main version format is incorrect. Must be in the format (e.g.) v1.5.1.dev36"
            exit 1
          fi
          echo "Using version: $version"
          echo version=$version >> $GITHUB_OUTPUT

      - name: Set nightly tags
        id: tags
        run: |
          version="${{ steps.version.outputs.version }}"
          echo "docker_tags=langflowai/langflow-nightly:${version},langflowai/langflow-nightly:latest" >> $GITHUB_OUTPUT
          echo "ghcr_tags=ghcr.io/langflow-ai/langflow-nightly:${version},ghcr.io/langflow-ai/langflow-nightly:latest" >> $GITHUB_OUTPUT

      - name: Docker cleanup
        run: |
          docker system prune -af --volumes || true
          docker buildx prune -af || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TEMP_GHCR_TOKEN}}

      - name: Build and push nightly main to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          file: ./docker/build_and_push.Dockerfile
          tags: ${{ steps.tags.outputs.docker_tags }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push nightly main to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          file: ./docker/build_and_push.Dockerfile
          tags: ${{ steps.tags.outputs.ghcr_tags }}
          platforms: linux/amd64,linux/arm64

  # nightly-main-all includes all the extras
  build-nightly-main-all:
    name: Build Nightly Main All Package
    if: ${{ inputs.release_type == 'nightly-main-all' }}
    runs-on: [self-hosted, linux, ARM64, langflow-ai-arm64-40gb]
    steps:
      - name: Check out the code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Environment
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.13"
          prune-cache: false

      - name: Get version for tagging
        id: version
        run: |
          echo "Extracting main version from pyproject.toml"

          # Use the exact version from pyproject.toml (must already be formatted correctly)
          version=$(uv tree | grep 'langflow' | grep -v 'langflow-base' | awk '{print $2}' | sed 's/^v//')

          # Verify nightly tag format
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$ ]]; then
            echo "Main version format is incorrect. Must be in the format (e.g.) v1.5.1.dev36"
            exit 1
          fi
          echo "Using version: $version"
          echo version=$version >> $GITHUB_OUTPUT

      - name: Set nightly all tags
        id: tags
        run: |
          version="${{ steps.version.outputs.version }}"
          echo "docker_tags=langflowai/langflow-all-nightly:${version},langflowai/langflow-all-nightly:latest" >> $GITHUB_OUTPUT
          echo "ghcr_tags=ghcr.io/langflow-ai/langflow-all-nightly:${version},ghcr.io/langflow-ai/langflow-all-nightly:latest" >> $GITHUB_OUTPUT

      - name: Docker cleanup
        run: |
          docker system prune -af --volumes || true
          docker buildx prune -af || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TEMP_GHCR_TOKEN}}

      - name: Build and push nightly main-all to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          file: ./docker/build_and_push_with_extras.Dockerfile
          tags: ${{ steps.tags.outputs.docker_tags }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push nightly main-all to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          file: ./docker/build_and_push_with_extras.Dockerfile
          tags: ${{ steps.tags.outputs.ghcr_tags }}
          platforms: linux/amd64,linux/arm64